version: 2

sources:
  - name: ZELLER                   # Logical source name for dbt
    database: ZELLER               # Snowflake database name
    tables:
      - name: TRANSACTIONS         # Table name in Snowflake
        schema: TRANSACTIONS       # Schema name in Snowflake
      - name: MERCHANT
        schema: MERCHANT